name: cfnews
description: A Flutter application for reading news

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.9.1
  equatable: ^0.2.3
  built_value: ^6.6.0
  built_collection: ^4.2.2
  kiwi: ^0.1.0
  http: ^0.12.0+2
  intl: ^0.15.8
  path_provider: ^1.1.2
  sembast: ^1.15.4+1
  timeago: ^2.0.16
  url_launcher: ^5.0.2
  flutter_svg: ^0.13.1
  flutter_advanced_networkimage: ^0.5.0
  share: ^0.6.1+1
  flushbar: ^1.7.1+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.0
  built_value_generator: ^6.6.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1x1_transparent.png
    - assets/images/background_image.jpg
    - assets/images/missing_image.png
    - assets/images/logo.png

